### ISSUE TITLE
Verificar se há erros antes de parsear

### ISSUE THREAD

**Issue by gpedro** [juniorb2ss/zrf#1]
Após consulta, caso o CNPJ não exista ou ocorra algum outro tipo de erro não esperado, a SRF retorna para esta url `http://www.receita.fazenda.gov.br/pessoajuridica/cnpj/cnpjreva/Cnpjreva_Erro.asp`, que tem um parametro **erro** onde há a mensagem do erro.

> http://www.receita.fazenda.gov.br/pessoajuridica/cnpj/cnpjreva/Cnpjreva_Erro.asp?erro=O%20n%FAmero%20do%20CNPJ%20n%E3o%20%E9%20v%E1lido.%20Verifique%20se%20o%20mesmo%20foi%20digitado%20corretamente

**Comment by juniorb2ss** [comment]
Bem ressaltado. Vou implementar alteração mais rápido possível :+1:

**Comment by juniorb2ss** [comment]
Feat commit:  https://github.com/juniorb2ss/zrf/commit/163622f3708c9e79878241881869967230a4a0d7

Obrigado
