### ISSUE TITLE
Coerente implementar DeathByCaptcha?

### ISSUE THREAD

**Issue by juniorb2ss** [juniorb2ss/zrf#3]
DeathByCaptcha é um serviço de automação de quebra de captcha, é um serviço pago que disponibiliza uma API de requisição. Você envia a imagem do captcha, entre alguns segundos ele retorna o captcha resolvido.

A principio seria uma implementação afins de "complementação", mas com responsabilidade de quem utilizar a automação.

É coerente?

**Comment by dfalbel** [comment]
Acredito que seja coerente. Se a informação é pública ela deve ser acessível (senão não deveria ser pública) e então não deveria ser protegida por captchas...

Poderíamos tentar integrar com o pacote em R que eu e o @jtrecenti desenvolvemos. 

https://github.com/dfalbel/captchaReceita2

Vamos conversar?

**Comment by juniorb2ss** [comment]
@dfalbel eu também levo comigo este pensamento, porém, infelizmente no Brasil temos vários problemas quanto a isso. Eu gostaria muito de disponibilizar um pacote para este intuito, claro, com responsabilidade de quem utilizar. Mas apoio fortemente o livre acesso a dados publicos. Eu vi este pacote, achei muito interessante e seria um diferencial imenso para bibilioteca uma integração. O que acha?

Estou reformulando o pacote com maior organização e serviços de outros portais:

https://github.com/juniorb2ss/zServices

Já esta implementado informações do SINTEGRA de SP, qual também possui o captcha.

**Comment by jtrecenti** [comment]
Eu já fiz integração com deathbycaptcha antes e em R, mas não fiz a parte
de autenticação bem feita. Acho que é interessante fazer um pacote em
separado para deathbycaptcha, pq ele é de propósito geral.

Em dom, 1 de mai de 2016 18:34, Carlos Eduardo notifications@github.com
escreveu:

**Comment by juniorb2ss** [comment]
@jtrecenti Sim, será separado. Vou abstrair biblioteca em outro pacote e fazer referencia.

**Comment by juniorb2ss** [comment]
@dfalbel o que pensa sobre um junção das ferramentas?

**Comment by juniorb2ss** [comment]
@jtrecenti segue biblioteca para o uso do DBC: https://github.com/juniorb2ss/Captcha

**Comment by juniorb2ss** [comment]
Fix: https://github.com/juniorb2ss/zServices/commit/dce35f456e841057ddce80b9ccd569f9a315a43a
